<h1 class="text-center mb-4">Group List</h1>

<div class="d-md-flex d-block justify-content-between mb-2">
    <div class="d-md-flex align-items-center d-block mb-md-0 mb-2 text-md-left text-center">
        Total: <?= $total ?>
    </div>
    <div class="d-md-flex d-block align-items-center gap-2">
        <form action="/groups" method="get" class="mb-md-0 mb-2">
            <div class="input-group">
                <input type="hidden" name="page" value="<?= $page ?>">
                <input type="hidden" name="limit" value="<?= $limit ?>">
                <input type="text" name="q" class="form-control" placeholder="Search by *" value="<?= $_GET['q'] ?? '' ?>">
                <button type="submit" class="btn btn-dark">Search</button>
            </div>
        </form>
        <div class="dropdown mb-md-0 mb-2">
            <button class="btn btn-secondary dropdown-toggle w-100" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Limit: <?= $limit ?>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <?php
                    foreach ([10, 25, 50, 100] as $i) {
                        $active = ($i === $limit) ? 'active' : '';
                        $href = "/groups?limit=" . $i . "&page=" . $page;
                        echo '<li><a class="dropdown-item ' . $active . '" href="' .$href. '">' . $i . '</a></li>';
                    }
                ?>
            </ul>
        </div>
        <a href="/groups/create" class="btn btn-primary">Add New Group</a>
    </div>
</div>
<div style="overflow-x: auto">
    <table class="table table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th class="text-center">#</th>
                <th>Group Name</th>
                <th>Parent Groups</th>
                <th class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php if (!empty($groups)): ?>
                <?php foreach ($groups as $index => $group): ?>
                    <tr>
                        <td class="text-center align-middle" style="width: 4rem"><?= $index + 1 ?></td>
                        <td class="align-middle"><?= htmlspecialchars($group['name']) ?></td>
                        <td class="align-middle"><?= $group['parent_group_names'] ?></td>
                        <td class='text-center' style="width: 10rem">
                            <a href="/groups/edit?id=<?= htmlspecialchars($group['id']) ?>" class="btn btn-sm w-100 mb-2 btn-warning">Edit</a>
                            <a href="/groups/delete?id=<?= htmlspecialchars($group['id']) ?>" class="btn btn-sm w-100 mb-2 btn-danger" onclick="return confirm('Are you sure you want to delete this group?');">Delete</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="4" class="text-center">No groups found.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>
<div aria-label="Page navigation example">
  <ul class="pagination justify-content-end">
    <li class="page-item">
      <a class="page-link <?php if ($page === 1): echo "disabled"; endif; ?>" href="/groups?limit=<?= $limit ?>&page=<?= $page - 1 ? $page - 1 : 1 ?>" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    <?php
        if($total > $page * 10) {
            $start = max($page, $page - 3);
            $end = min($total, $page + 3);
            for ($i = $start; $i <= $end; $i++) {
                $active = ($i === $page) ? 'active' : '';
                echo '<li class="page-item ' . $active . '"><a class="page-link" href="/groups?limit=' . $limit . '&page=' . $i . '">' . $i . '</a></li>';
            }
        }
    ?>
    <a class="page-link <?php if ($total/$limit <= $page): echo "disabled"; endif; ?>" href="/groups?limit=<?= $limit ?>&page=<?= $page + 1 ?>" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
  </ul>
</div>