<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Address Book</title>
    <!-- Bootstrap CSS (CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/style.css"> <!-- Custom CSS (Optional) -->
</head>
<body>
    <!-- Header -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <img src="/logo.png" alt="Logo" width="30" height="30" class="d-inline-block align-top"/> Address Book
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/cities">Cities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/create">Add Address</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <?php use App\Helpers\Notification; ?>

<?php foreach (Notification::get() as $notification): ?>
    <div class="alert alert-<?= $notification['type']; ?>" role="alert">
        <div class="container">
            <?= htmlspecialchars($notification['message']); ?>
        </div>
    </div>
<?php endforeach; ?>
    <!-- Main Content Area -->
     <main class="layout">
        <div class="container my-4">
            <?php echo $content; ?>
        </div>
     </main>

    <!-- Footer -->
    <footer class="bg-light text-center py-3">
        <p>&copy; 2025 Address Book. All rights reserved.</p>
    </footer>

    <!-- Bootstrap JS (CDN) -->
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="js/script.js"></script> <!-- Custom JS (Optional) -->
</body>
</html>
